# Generated by Django 2.2.4 on 2020-08-14 12:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0002_result_percent_matching'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'mercury_equipmenttype',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='merlinservices.EquipmentType')),
            ],
            options={
                'db_table': 'mercury_equipment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BalanceVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verification_time', models.TimeField(blank=True, null=True)),
                ('weight_tested', models.FloatField(blank=True, null=True)),
                ('weight_as_found', models.FloatField(blank=True, null=True)),
                ('deviation', models.FloatField(blank=True, null=True)),
                ('percent_deviation', models.IntegerField(blank=True, null=True)),
                ('final_reading', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_verifications', to='merlinservices.UserProfile')),
                ('balance', models.ForeignKey(limit_choices_to={'type': 'balance'}, on_delete=django.db.models.deletion.CASCADE, related_name='balance_verifications', to='merlinservices.Equipment')),
            ],
            options={
                'db_table': 'mercury_balanceverification',
                'ordering': ['-id'],
            },
        ),
    ]
