# Generated by Django 2.2.24 on 2021-11-05 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0004_auto_20201005_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balanceverification',
            old_name='percent_deviation',
            new_name='percent_recovery',
        ),
    ]
