# Generated by Django 2.2.24 on 2022-06-29 13:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merlinservices', '0005_auto_20211105_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('verification_time', models.TimeField(blank=True, null=True)),
                ('weight_tested', models.FloatField(blank=True, null=True)),
                ('weight_as_found', models.FloatField(blank=True, null=True)),
                ('deviation', models.FloatField(blank=True, null=True)),
                ('percent_recovery', models.IntegerField(blank=True, null=True)),
                ('final_reading', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('analyst', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mercury_equipmentverification',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='acid',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='blankwater',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='bottleprefix',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='bromination',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='samplebottle',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='samplebottlebromination',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.DeleteModel(
            name='BalanceVerification',
        ),
        migrations.AddField(
            model_name='equipmentverification',
            name='equipment',
            field=models.ForeignKey(limit_choices_to={'type': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_verifications', to='merlinservices.Equipment'),
        ),
    ]
