# Generated by Django 2.2.24 on 2021-09-27 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0005_auto_20210927_1646'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QualityAssurance',
            new_name='ResultQualityAssuranceFlag',
        ),
        migrations.AlterModelTable(
            name='resultqualityassuranceflag',
            table='mercury_resultqualityassuranceflag',
        ),
    ]
