# Generated by Django 2.2.24 on 2021-09-29 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0006_auto_20210927_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAssuranceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'mercury_qualityassurancetype',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MethodQualityAssurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True)),
                ('observed_date', models.DateField(blank=True, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assurances', to='merlinservices.MethodType')),
                ('quality_assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlinservices.QualityAssuranceType')),
            ],
            options={
                'db_table': 'mercury_methodqualityassurance',
                'ordering': ['-id'],
                'unique_together': {('quality_assurance', 'method')},
            },
        ),
    ]
