# Generated by Django 2.2.24 on 2022-06-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0006_auto_20220629_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentverification',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_verifications', to='merlinservices.Equipment'),
        ),
    ]
