# Generated by Django 2.2.24 on 2022-05-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0005_auto_20211105_1503'),
        ('merlinservices', '0007_methodqualityassurance_qualityassurancetype'),
    ]

    operations = [
    ]
