# Generated by Django 2.2.24 on 2022-05-23 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0008_merge_20220523_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_description', models.TextField(blank=True)),
                ('analytical_description', models.TextField(blank=True)),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('bottle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standards', to='merlinservices.Bottle')),
                ('concentration_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concentration_unit', to='merlinservices.UnitType')),
            ],
            options={
                'db_table': 'mercury_standardtype',
                'ordering': ['-id'],
            },
        ),
    ]
