# Generated by Django 2.2.24 on 2022-05-23 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0009_standardtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='methodqualityassurance',
            old_name='observed_date',
            new_name='analyzed_date',
        ),
        migrations.AddField(
            model_name='methodqualityassurance',
            name='analytical_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='methodqualityassurance',
            name='analytical_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quality_assurances', to='merlinservices.Equipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='methodqualityassurance',
            name='batch_setup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='methodqualityassurance',
            name='bottle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_assurances', to='merlinservices.StandardType'),
        ),
        migrations.AddField(
            model_name='methodqualityassurance',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='methodqualityassurance',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='methodqualityassurance',
            name='instance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='methodqualityassurance',
            name='modified_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='methodqualityassurance',
            name='quality_assurance_flag',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='merlinservices.QualityAssuranceFlag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='methodqualityassurance',
            name='quality_assurance_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_assurance_units', to='merlinservices.UnitType'),
        ),
        migrations.AlterField(
            model_name='methodqualityassurance',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
