# Generated by Django 2.2.24 on 2022-05-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0010_auto_20220523_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottleQualityAssuranceCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'mercury_bottlequalityassurancecode',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='methodqualityassurance',
            name='bottle_quality_assurance_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merlinservices.BottleQualityAssuranceCode'),
        ),
    ]
