# Generated by Django 2.2.24 on 2022-05-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0011_auto_20220527_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StandardType',
            new_name='Standard',
        ),
        migrations.AlterModelTable(
            name='standard',
            table='mercury_standard',
        ),
    ]
