# Generated by Django 2.2.24 on 2022-06-08 12:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0012_auto_20220531_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityAssurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analytical_description', models.TextField(blank=True)),
                ('instance', models.IntegerField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('comment', models.TextField(blank=True)),
                ('batch_setup_date', models.DateField(blank=True, null=True)),
                ('analyzed_date', models.DateField(blank=True, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('modified_date', models.DateField(auto_now=True, null=True)),
                ('analytical_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assurances', to='merlinservices.Equipment')),
                ('bottle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_assurances', to='merlinservices.Standard')),
                ('bottle_quality_assurance_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merlinservices.BottleQualityAssuranceCode')),
                ('quality_assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlinservices.QualityAssuranceType')),
                ('quality_assurance_flag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='merlinservices.QualityAssuranceFlag')),
                ('quality_assurance_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_assurance_units', to='merlinservices.UnitType')),
            ],
            options={
                'db_table': 'mercury_qualityassurance',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='MethodQualityAssurance',
        ),
    ]
