# Generated by Django 2.2.24 on 2022-06-16 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0013_auto_20220608_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qualityassurance',
            old_name='bottle',
            new_name='standard',
        ),
        migrations.AlterField(
            model_name='acid',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='balanceverification',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='blankwater',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='bottleprefix',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='bromination',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='qualityassurance',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='samplebottle',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='samplebottlebromination',
            name='created_date',
            field=models.DateField(blank=True, db_index=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='standard',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
