# Generated by Django 2.2.24 on 2022-06-16 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0014_auto_20220616_1147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BottleQualityAssuranceCode',
            new_name='StandardQualityAssuranceCode',
        ),
        migrations.RenameField(
            model_name='qualityassurance',
            old_name='bottle_quality_assurance_code',
            new_name='standard_quality_assurance_code',
        ),
    ]
