# Generated by Django 2.2.24 on 2022-06-16 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0015_auto_20220616_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualityassurance',
            name='quality_assurance_flag',
        ),
        migrations.CreateModel(
            name='QualityAssuranceQualityAssuranceFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_assurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_assurance_flags', to='merlinservices.QualityAssurance')),
                ('quality_assurance_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merlinservices.QualityAssuranceFlag')),
            ],
            options={
                'db_table': 'mercury_qualityassurancequalityassuranceflag',
                'ordering': ['-id'],
                'unique_together': {('quality_assurance_flag', 'quality_assurance')},
            },
        ),
    ]
