# Generated by Django 2.2.24 on 2022-06-28 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merlinservices', '0016_auto_20220616_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityassurance',
            name='method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='merlinservices.MethodType'),
            preserve_default=False,
        ),
    ]
