# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-11 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercuryservices', '0002_auto_20180117_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottleprefix',
            name='tare_weight',
        ),
        migrations.AddField(
            model_name='bottle',
            name='tare_weight',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
    ]
