INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (2, 'Lake Powell', 'a study of a reservoir', '123456', 4);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (3, 'Lake Mead', 'another study of a reservoir', '98765', 4);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (4, 'MDL', 'MINIMUM DETECTION LIMIT STUDIES', '', 81);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (5, 'GUSTAVUS STREAMS', 'MERCURY IN STREAMS NEAR GUSTAVUS ALASKA', 'GX11WB20DZT0000', 50);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (6, 'COLORADO RESERVOIR STUDY', 'MERCURY IN COLORADO RESERVOIRS', '8582BC299', 51);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (7, 'IDAHO STATEWIDE WATER QUALITY', 'STATEWIDE WATER QUALITY NETWORK FOR IDAHO', '969700300', 103);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (8, 'YUKON', 'YUKON RIVER BASIN BASELINE STUDY', '445519704', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (9, 'SURINAM', 'SURINAM - GROS ROSEBELL', '', 89);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (10, 'OAKLAND COUNTY BACTERIA', 'OAKLAND COUNTY BACTERIA', '', 46);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (11, 'QCTYPES', 'QC TYPES USED IN ANALYSIS FOR QUALITY CONTROL', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (12, 'MORGAN_TEST', 'USED FOR TEST DATA', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (13, 'PACIFIC CRUISE', 'PACIFIC CRUISE', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (14, 'ENHANCED ENGLESBY', '', '2450A71EE', 60);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (15, 'ANACOSTIA', 'ANACOSTIA BASIN, MARYLAND', '', 117);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (16, 'WEEKS BAY', 'WEEKS BAY TRAILER DEPLOYMENT', '', 76);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (17, 'LAKE MICH TRIBS', 'LAKE MICH TRIBS', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (18, 'RED RIVER', 'RED RIVER BASIN IMPOUNDMENTS', '', 61);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (19, 'ND', 'NORTH DAKOTA', '463821700', 58);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (20, 'UTAH SNOW', 'UTAH SNOW', '445519704', 36);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (21, 'ST CROIX TRIBUTARIES', 'ST CROIX TRIBUTARIES', '462717500', 61);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (22, 'PHILIPPINES', 'PALAWAN QUICKSILVER MINE, PHILIPPINES', '', 89);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (23, 'LAHONTAN RESERVOIR', 'LAHONTAN RESERVOIR STUDY WITH MARK MARVIN-DIPASQUALE', '438721500', 106);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (24, 'NATIONAL LAKE ASSESSMENT', 'NATIONAL LAKE ASSESSMENT', 'AK710', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (25, 'GLACIAL RIDGE', 'MERCURY ASSESSMENT FOR GLACIAL RIDGE WILDLIFE REFUGE', '860797L99', 144);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (26, 'GLACIER BAY', 'MERCURY OCCURENCE IN TRIBUTARY STREAMS TO GLACIER BAY, ALASKA', 'AK710', 132);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (27, 'DUCK VALLEY FISH TISSUE', 'MERCURY ASSESSMENT PROJECT FOR THE SHOSHONE-PIAUTE TRIBE ON THE DUCK VALLEY RESERVATION', 'GC13YE00F97GS00', 94);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (28, 'UTAH DEQ', 'GREAT SALT LAKE MERCURY FOR UTAH DEPARTMENT OF ENVIRONMENTAL QUALITY', '', 145);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (29, 'FLATHEAD QW', 'WATER-QUALITY SAMPLING IN THE UPPER FLATHEAD RIVER WATERSHED', '862000300', 108);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (30, 'OHIO MERCURY SYNOPTIC', 'SYNOPTIC SURVEY OF STREAMS IN OHIO', '247200A00', 47);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (31, 'SAN JOAQUIN RIVER', 'MERCURY IN THE SAN JOAQUIN RIVER SYSTEM', 'AK710', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (32, 'BLM - SAILOR FLAT MINE', '', '9677bq525', 146);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (33, 'BRABETS -- WONDER LAKE', 'NASQAN SAMPLING AT WOMDER LAKE', '', 148);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (34, 'INDIANA', 'GRAND CALUMET MERCURY', '441823600', 100);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (35, 'YOLO BYPASS', 'YOLO BYPASS - CACHE CREEK WETLANDS', '9677OAZ33', 156);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (36, 'MENOMENEE', 'MENOMENEE', '', 121);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (37, 'HG + AS', 'GREAT EGG HARBOR RIVER BASIN MERCURY AND ARSENIC STUDY', '2454CK801', 131);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (38, 'DRY DOWN REWET', 'DRY DOWN REWET EXPERIMENT ON GLADES SEDIMENTS', '', 37);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (39, 'NAWQA GROUNDWATER', 'GROUNDWATER SAMPLING FOR NAWQA IN NEW JERSEY', '2454CRKLB', 149);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (40, 'PUERTO RICO WEBB', 'PUERTO RICO WEBB', '', 74);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (41, 'FWS - GREAT SALT LAKE', 'FISH AND WILDLIFE SERVICE GREAT SALT LAKE', '', 56);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (42, 'ORLANDO', 'UNIVERISTY OF CENTRA FLORIDA -- ORLANDO', '', 42);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (43, 'SOUTH RIVER', 'SOUTH RIVER MERCURY TMDL', '24829ROX9', 90);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (44, 'FALLON NEVADA CLUSTER', 'FALLON NEVADA HUMAN HEALTH CLUSTER STUDY', '473288851', 40);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (45, 'MT. MCKINLEY SNOW CHEMISTRY', 'SYNOPTIC SAMPLING OF SNOW SAMPLES FROM MT. MCKINLEY', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (46, 'YANKTON SIOUX', 'YANKTON SIOUX TRIBE WETLANDS -- SOUTH DAKOTA', '8648BS060', 151);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (47, 'SONOMA COUNTY WATER QUALITY', 'WATER QUALITY IN SONOMA COUNTY CALIFORNIA', '9677BRO00', 101);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (48, 'NJ - FTHG SYNOPTIC', 'NJ - FTHG SYNOPTIC DATA', '2454003LB', 59);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (49, 'OUACHITA RIVER', 'OACHITA RIVER LOW-LEVEL HG', 'GX12SF00001RS00 ', 120);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (50, 'USFWS LOSTWOOD', 'US FISH AND WILDLIFE SERVICE - LOSTWOOD NATIONAL WILDLIFE REFUGE', '', 49);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (51, 'NORDSTROM -- YNP', 'YELLOWSTONE NATION PARK -- KIRK NORDSTROM', '', 104);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (52, 'GUADALUPE RESERVOIR', '', '4559OD200', 106);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (53, 'USFWS MOBILE BAY', 'US FISH AND WILDLIFE IN MOBILE BAY WATERSHED', '2499BA1WB', 92);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (54, 'BEAR-YUBA', 'BEAR AND YUBA RIVER ACID MINE', '', 33);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (55, 'CARSON', 'CARSON RIVER SUPERFUND', ' GR12ZJ00A520900', 143);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (56, 'COEUR D ALENE', 'LAKE COEUR D ALENE', '', 122);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (57, 'CRANDON', 'CRANDON', '445500201', 119);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (58, 'ELA', 'ENVIRONMENTAL LAKES AREA, ONTARIO', '445519702', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (59, 'EVERGLADES', 'SOUTH FLORIDA RESTORATION INITIATIVE', '445519700', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (60, 'NAWQA PILOT', 'NAWQA PILOT', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (61, 'NEW JERSEY GROUNDWATER', 'NEW JERSEY MECURY LAND USE-GROUNDWATER', '', 83);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (62, 'NPS', 'NATIONAL PARKS SERVICE', '', 125);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (63, 'QA', 'QUALITY CONTROL FOR USGS LAB', '', 78);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (64, 'SAC NAWQA', 'SAC NATIONAL WATER QUALITY ASSESSMENT PROGRAM', '470650400', 152);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (65, 'SD', 'SOUTH DAKOTA', '', 58);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (66, 'SF BAY', 'SAN FRANCISCO BAY - DELTA PROJECT', '', 106);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (67, 'SOFL', 'SOUTH FLORIDA NAWQA - ASR PROJECT (459800301)', '', 63);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (68, 'TIEN SHAN', 'SYNOPTIC SAMPLING OF SNOW SAMPLES FROM THE TIEN SHAN MOUNTAINS, CHINA', '', 138);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (69, 'NECB NAWQA', 'NEW ENGLAND COASTAL BASIN NAWQA', '', 123);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (70, 'GRSL NAWQA', 'GREAT SALT LAKE BASIN NAWQA', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (71, 'VOYAGEURS', 'VOYAGEURS', '462717400', 61);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (72, 'PUERTO RICO SURFACEWATER SAMPL', 'SURFACE WATER SAMPLING IN PUERTO RICO', 'GC11MJ00003000', 44);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (73, 'WALKER RIVER MERCURY', 'WALKER RIVER MERCURY', '473200351', 141);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (74, 'DELR NAWQA', 'DELAWARE NAWQA', '', 153);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (75, 'LACROSSE BRD', 'UPPER MIDWEST ENVIRONMENTAL SCIENCES CENTER LACROSSE, WI (UMESC)', '', 129);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (76, 'NASQAN', 'NASQAN PROGRAM SAMPLING AT LARGE RIVER SITES', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (77, 'VAN METER CORES', 'SEDIMENTS SAMPLES FROM THE DATED SEDIMENT CORES COLLECTED BY PETER VAN METRE', '', 140);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (78, 'MAURICE-COHANSEY', 'NEW JERSEY ADDITIONAL WORK', '443419100', 114);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (79, 'CHAMPLAIN', 'LAKE CHAMPLAIN MASS BALANCE', '443308100', 60);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (80, 'HBN', 'HYDROLOGIC BENCHMARK NETWORK PROGRAM SAMPLING', '462700300', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (81, 'JEAN LAFITTE NATIONAL PARK', 'JEAN LAFITTE NATIONAL PARK', '462214101', 26);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (82, 'FLORIDA BAY', 'FLORIDA BAY MERCURY METHYLATION STUDY', '', 115);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (83, 'MARVIN-DIPASQUALE', 'EXPERIMETNTAL STUDIES WITH MARK MARVIN DIPASQUALE', '', 96);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (84, 'NASQAN II', 'NASQAN PROGRAM SAMPLING AT LARGE RIVER SITES II', '464800333', 107);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (85, 'ARMI', 'AMPHIBIANS RESEARCH AND MONITORING INITIATIVE', '438642700', 38);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (86, 'NAWQA HG STATUS', 'NAWQA HG STATUS 2002', '', 61);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (87, 'CFW RES', 'CAMP FAR WEST RESERVOIR', '2-438736000', 106);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (88, 'ROCKY MOUNTAIN SNOWPACK', 'SYNOPTIC SAMPLING OF SNOW SAMPLES FROM THE ROCKY MOUNTAINS', 'GR13RE009Y6X900', 79);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (89, 'LOSTWOOD', 'LOSTWOOD NATIONAL WILDLIFE REFUGE', '', 58);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (90, 'SOUTH SAN FRANCISCO BAY', 'SAN FRANCISCO BAY - DELTA PROJECT', '', 106);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (91, 'DELTA NATIONAL FOREST', 'DELTA NATIONAL FOREST', '', 120);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (92, 'BRETON SOUND', 'BRETON SOUND', '', 55);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (93, 'WACAP', 'WACAP', '', 79);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (94, 'SILVER CREEK', 'SILVER CREEK', '', 108);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (95, 'YNP', 'YELLOWSTONE NATIONAL PARK', '', 110);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (96, 'MI TRIBES', 'MICHIGAN DISTRICT TRIBES', 'GR11NH00001NP00', 77);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (97, 'MOREAU', 'MICROBIAL STUDIES', 'INTERNAL', 113);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (98, 'AUDIT-INTERCOMP', 'AUDIT-INTERCOMP', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (99, 'MSI', 'MOUNTAIN STUDIES INSTITUTE', '', 155);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (100, 'BLM - MICHIGAN BLUFF MINE', '', '9677bq523', 146);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (101, 'BLM - BADGER HILL MINE', '', '9677bq525', 146);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (102, 'MERCURY VARIABILITY', 'VARIABILITY OF MERCURY DURING WELL PURGING', '', 131);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (103, 'SINCLAIR INLET', 'POTENTIAL SOURCES OF MERCURY IN SINCLAIR INLET', '9722D6M00', 34);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (104, 'MERCURY IN LITTERFALL', 'MERCURY IN LITTERFALL NEAR MDN SITES', '', 100);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (105, 'CROOKED CREEK', 'CROOKED CREEK ALASKA', 'GC11WB200010G1G', 69);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (106, 'PERMAFROST', 'PERMAFROST FROM ALASKA', '', 82);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (107, 'PENNSYLVANIA STREAMS', 'MERCURY IN PENNSYLVANIA STREAMS', '', 41);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (108, 'GREAT LAKES MERCURY', '', '', 136);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (109, 'UTAH SW BASIC DATA', 'UTAH BASIC DATA SECTION', 'GC13ZK000010001', 84);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (110, 'LADOTD LAKE STUDY', 'LOUISIANA LAKE STUDY', 'GC14SF00AGD3200', 109);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (111, 'HAWAII', '', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (112, 'SILVER RIVER', 'SILVER RIVER MERCURY STUDY', '214500370', 77);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (113, 'CARBON FARMING - CALIFORNIA', 'CARBON SEQUESTRATION PROJECT IN CALIFORNIA', '9kl28', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (114, 'NPS - ENP', 'EVERGLADES NATIONAL PARK COLLABORATION WITH NATIONAL PARK SERVICE', '9kl28', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (115, 'SQUANKUM HG TRACKDOWN', 'SQUANKUM MERCURY TRACKDOWN', '2454ck8lb', 131);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (116, 'NLA SEDIMENTS', 'SEDIMENTS FROM EPA NATIONAL LAKES SURVEY', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (117, 'TWITCHELL RICE', 'TWITCHELL ISLAND RICE PROJECT', 'GC11ZG00DZGJF00', 146);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (118, 'NORMAN LANDFILL', '', '', 95);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (119, 'SOUTHERN OCEAN CRUISE', 'SOUTHERN OCEAN CRUISE', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (120, 'HG BIOACCUMULATION FACTORS', 'STUDY OF MERCURY BIOACCUMULATION FACTORRS IN NEW JERSEY', '2454003LH', 112);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (121, 'MARCELL EXPERIMENTAL FOREST', '', '', 146);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (122, 'EPA ATHENS SOIL', 'EPA ATHENS SOIL MERCURY PROJECT', '', 61);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (123, 'YOLO WILDLIFE AREA', '', '', 146);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (124, 'CHURCHHILL COUNTY POLONIUM', '', '9705DGNPX', 91);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (125, 'CROSSWICKS HG TMDL', 'CROSSWICKS HG TMDL', '2454-CK8LB', 150);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (126, 'MI - HG/SE INTERACTIONS', 'MERCURY/SELENIUM INTERACTIONS IN UPPER MICHIGAN MINING AREA', '9KL12', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (127, 'ACADIA NATIONAL PARK', 'MERCURY IN ACADIA NATIONAL PARK, MAINE', 'AK710', 67);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (128, 'NEWCASTLE RESERVOIR', 'MERCURY IN THE NEWCASTLE RESERVOIR, UTAH', 'GC12ZK00E7Y0100 ', 97);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (129, 'AMERICAN SAMOA LANDFILL', '', 'GX12ZK00EK40000', 62);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (130, 'HONNEDAGA MERCURY', 'HONNEDAGA MERCURY', 'GC12LK00LBEX500', 142);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (131, 'OTTAWA MERCURY', 'MERCURY IN WETLANDS ADJACENT TO GREAT LAKES', '', 111);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (132, 'KICKAPOO CREEK AND WETLANDS', 'KICKAPOO CREEK AND WETLANDS', 'D7Q00', 93);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (133, 'ATLANTIC HIGHLANDS', 'SEDIMENT MERCURY DEPOSITION IN HIGHLNADS OF THE US', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (134, 'MIDDLETON AIRPORT', '', '', 147);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (135, 'JUNEAU WETLANDS', '', '', 132);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (136, 'POWDER RIVER BASIN COAL', '', '', 35);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (137, 'ITPC', 'INTERTIDAL PARTICLE CHARACTERIZATION', '', 146);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (138, 'GRANT RESEARCH GROUP', 'CHRIS GRANT RESEARCH -- JUNIATA COLLEGE', 'jfa -- juniata', 41);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (139, 'LSNERR - ST LOUIS RIVER', 'MERCURY IN SEDIMENT OF THE ST LOUIS RIVER', '', 31);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (140, 'LICD - MESOCOSMS', 'MESOCOSM STUDY AT CALIFORNIA LICD', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (141, 'NPS - DRAGONFLY', '', '', 28);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (142, 'BARROW', '', '9KL12', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (143, 'COLUMBIA RIVER INPUTS', 'IN PUTS TO THE COLUMBIA RIVER', '9711-00303', 105);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (144, 'TUMACACORI', 'TUMACACORI EMERGING CONTAMINANTS', 'GR11ZF00EG70200', 53);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (145, 'HUMBOLDT', 'HUMBOLDT DRAINAGE BASIN, NEVADA', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (146, 'DAVES METHYLATION EXPERIMENT', '', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (147, 'KUSKOKWIM TRIBUTARIES', 'TRIBUTARIES TO THE KUSKOKWIM RIVER, AK', '8928-MJ8JG', 69);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (148, 'BLACKFOOT RESERVOIR', '', 'AK710', 128);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (149, 'YUKON LAKES', '', '', 82);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (150, 'LAKE FORT SMITH', 'LAKE FORT SMITH MERCURY', 'GC12SD00ES4OC00
', 116);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (151, '2012 NLA SEDIMENTS', '', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (152, 'TRASK RIVER WATERSHED', 'TRASK RIVER WATERSHED LOGGING EXPERIMENT', '', 35);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (153, 'OHIO RIVER MERCURY', 'MERCURY IN THE OHIO RIVER', '2419-E7VU1', 85);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (154, 'MISSISSIPPI AEROSOLS', 'AEROSOLS IN THE MISSISSIPPI DELTA', '2791-AK710', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (155, 'LAHONTAN RESERVOIR SUPERFUND', '', '9705-A5211', 91);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (156, 'LOUISIANA OILSPILL RESPONSE', '', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (157, 'MICHIGAN TECH', 'HG IN MOOSE AND BEAVER FORAGE', '', 126);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (158, 'CORNELL BRAZIL', 'CORNELL BRAZIL', '', 122);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (159, 'DEVILS HOLE CHEMISTRY', 'DEVILS HOLE CHEMISTRY', '9705A6J01', 64);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (160, 'PONTCHARTRAIN', 'LAKE PONTCHARTRAIN', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (161, 'FLORIDA ASR', 'FLORIDA GROUNDWATER WELLS', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (162, 'MN HG-FLUX', 'MERCURY FLUX CHAMBER WORK', '860717900', 70);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (163, 'LONG NECK MERCURY', 'MERCURY IN GROUNDWATER', '2427B5B00', 98);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (164, 'NTL-WEBB', 'NORTHERN TEMPERATE LAKES WEBB', '', 124);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (165, 'DIEL METAL CYCLING', 'MERCURY CYCLING IN MONTANA', '862018600', 72);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (166, 'LAKE MENDOTA', '', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (167, 'ROMO - MPB', 'LOCH VALE - MOUNTAIN PINE BEETLE', 'GX13RE00F7C0900', 27);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (168, 'LAKEWOOD DATA PROGRAM', '', 'GC12RE000032900
', 86);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (169, 'GREAT SALT LAKE MINERALS', '', '', 52);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (170, 'BONANZA CREEK EXPERIMENTAL', 'EXPERIMENTAL PLOT IN THE BONANZA CREEK WATERSHED, ALASKA', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (171, 'UW ANIMAL SCIENCE', '', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (172, 'CAPE SABLE SEASIDE SPARROW', '', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (173, 'HURON RIVER', 'HURON RIVER MERCURY STUDY', '2145DE62C', 77);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (174, 'MUDFLATS - SINCLAIR', 'MUDFLATS NEAR SINCLAIR INLET', '24919KL12', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (175, 'TWITCHELL COAGULATION', 'COAGULATION EXPERIMENT AT TWITCHELL ISLAND SITE', '', 48);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (176, 'WOODS HOLE', 'WOODS HOLE TRAILER DEPLOYMENT', '9KL12', 67);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (177, 'INDIANA RESERVOIRS', 'MERCURY IN INDIANA RESERVOIRS', '2412-9L020', 100);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (178, 'KENAI PENINSULA WETLANDS', '', '', 130);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (179, 'BONANZA HG MINE', 'BONANZA MERCURY MINE IN OREGON', '', 89);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (180, 'YELLOWSTONE-WDML', 'YELLOWSTONE NATIONAL PARK -WI DISTRICT MERCURY LAB', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (181, 'GREAT SALT LAKE', 'GREAT SALT LAKE BASIN NAWQA', 'GC12ZK000010001', 97);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (182, 'CHEQUAMEGON-NICOLET NATIONAL FOREST', '', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (183, 'ELS', 'EASTERN LAKES SURVEY', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (184, 'MMSD', 'MILWAUKEE METROPOLITAN SEWERAGE DISTRICT', '', 43);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (185, 'STANFORD TUNA', 'TUNA STUDY WITH STANFORD UNIVERSITY', '', 73);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (186, 'ALASKA REGIONAL', 'ALASKA REGIONAL', 'GX10WB30DVH03', 135);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (187, 'MOBILE BAY', 'MOBILE BAY', '2499BA1MB', 54);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (188, 'KNIFE POINT GLACIER', 'HIGH SCHOOL STUDENT PROJECT', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (189, 'SEWRPC', 'SOUTHEAST WISCONSIN REGIONAL PLANNING COMISSION', '9KM46', 29);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (190, 'PANOLA MTN WEBB', 'PANOLA MOUNTAIN WEBB', '2503AB250', 133);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (191, 'STARLIMS TEST PROJECT', 'FOR TESTING', '', 157);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (192, 'NOME CREEK', 'NOME CREEK BASIN MERCURY STUDY', '', 82);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (193, 'MIDWEST STREAM QUALITY ASSESSMENT', 'MIDWEST STREAM QUALITY ASSESSMENT', 'NAWQAMSQAFY13', 71);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (194, 'YUKON DELTA - SNOWY', '', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (195, 'SESQA', 'SOUTHEAST STREAM QUALITY ASSESSMENT', 'GX14DH00CRMRQ00', 71);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (196, 'HELLS CANYON COMPLEX', 'HELLS CANYON COMPLEX', '', 30);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (197, 'BOG - CALIFORNIA LAKES', 'MERCURY STUDY OF 5 CALIFORNIA LAKES', '', 118);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (198, 'MDN', 'MDN INTERCOMPARISON SAMPLES', '9KL12', 137);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (199, 'LOWER OUACHITA RIVER', 'LIAM SCHENK', '', 57);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (200, 'LEVIATHAN', 'LEVIATHAN, NEVADA', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (201, 'ACADIA SNOWPACK', 'ACADIA SNOWPACK', '', 102);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (202, 'TONGUE RIVER', 'MONTANA TONGUE RIVER MONITORING', '8620BE200', 87);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (203, 'SAN FRANCISCO BAY', 'SAN FRANCISCO BAY', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (204, 'MORAN', 'NATIONAL PARK SERVICE - HIGH LAKES', '9722-9EJ00', 134);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (205, 'LITTERFALL - RISCH', '', 'GR13NF009L14L00', 100);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (206, 'GREAT LAKES INPUTS', 'MERCURY INPUTS TO THE GREAT LAKES', '', 88);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (207, 'TAVASCI MARSH METALS', '', 'GX11ZF00ECD0000', 139);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (208, 'PENNSYLVANIA WATERSHED MERCURY PROJECT', '', '', 32);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (209, 'BAD RIVER MERCURY', 'MERCURY IN SURFACE WATER ON THE BAD RIVER INDIAN RESERVATION, WI', '', 66);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (210, 'UNIVERSITY OF IDAHO', 'UNIVERSITY OF IDAHO', 'JFA', 68);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (211, 'LICD - CALIFORNIA', 'LOW INTENSITY CHEMICAL DOSING', 'GC13ZG00D0U0000', 48);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (212, 'KELLYS SLOUGH NWR', '', '', 65);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (213, 'COTTAGE GROVE LAKE', '', 'GR12YF00003CG00 ', 99);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (214, 'COLORADO LTM', 'COLORADO LONG TERM LAKE MONITORING', 'GR12RE00BC29900', 51);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (215, 'STILLWATER NWR', 'STILLWATER NATIONAL WILDLIFE REFUGE HG', 'GR14ZJ00FG2S900', 91);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (216, 'ATLANTIC OCEAN', 'ATLANTIC OCEAN CRUISE', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (217, 'CONGO', '', '9KL12', 82);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (218, 'MISCELLANEOUS', 'MISCELLANEOUS PROJECTS', '9kl12', 81);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (219, 'LOCH VALE WEBB', 'LOCH VALE WEBB STUDY', 'GX12RE009Y3G900', 27);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (220, 'LAKE POWELL RECON', 'RECON OF LAKE POWELL', '9716-0az08', 97);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (221, 'BLM GW PICEANCE', 'GROUNDWATER STUDY IN PICEANCE BASIN', 'GR11RE00D9Y2900', 154);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (222, 'VICTORIA RESERVOIR', 'VICTORIA RESERVOIR, MICHIGAN ', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (223, 'RSQA - COLORADO', 'STREAM SEDIMENT FOR REGIONAL STREAM QUALITY ASSESSMENT', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (224, 'ARCTIC-GRO 2', 'ARCTIC RIVERS', '', 80);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (225, '2013 NLA SEDIMENTS', '', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (226, 'WEBSTER -- WILDFIRE', '', '', 75);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (227, 'UCRB BULK DEPOSITION', 'UPPER COLORADO RIVER BASIN MERCURY DEPOSITION', '8582-9y329', 45);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (228, 'ANTARCTIC OCEAN', 'ANTARCTIC OCEAN CRUISE', '', 127);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (229, 'BOISE RIVER WATER QUALITY', 'BOISE RIVER WATER QUALITY', 'GC14YE00FC3GS00', 103);
INSERT INTO "mercuryservices_project" ("id", "name", "description", "accounting_code", "cooperator_id") VALUES (230, 'BROWNLEE RESERVOIR', 'BROWNLEE RESERVOIR MERCURY STUDY', '', 39);
