INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (2, '"OA"', '"ARTIFICIAL"', '"ARTIFICIAL"', '"CREATED TO BE USED WITH TONY PAULSON''S INCUBATION EXPERIEMENTS"');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (3, '"WH"', '"HYPORHEIC"', '"HYPORHEIC ZONE"', '"ADDED 5/28/09"');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (4, '"WHQ"', '"HYPORHEIC REP"', '"HYPORHEIC ZONE"', '"ADDED 5/28/09"');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (5, '"WG"', '"GW"', '"GROUND WATER"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (6, '"WGQ"', '"GW REP"', '"GROUND WATER"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (7, '"WI"', '"PW"', '"PORE WATER"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (8, '"WIQ"', '"PW REP"', '"PORE WATER"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (9, '"SB"', '"SED"', '"SEDIMENT"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (10, '"SBQ"', '"SED REP"', '"SEDIMENT"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (11, '"WW"', '"PREC"', '"PRECIPITATION"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (12, '"WWQ"', '"PREC REP"', '"PRECIPITATION"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (13, '"OAQ"', '"QA"', '"QUALITY ASSURANCE"', '"QA IS PROJECT QA AND WILL BE LOADED INTO NWIS"');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (14, '"SO"', '"SOIL"', '"UPLAND SOIL SAMPLE"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (15, '"SOQ"', '"SOIL REP"', '"UPLAND SOIL SAMPLE"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (16, '"BA"', '"ANIMAL"', '"ANIMAL TISSUE"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (17, '"BAQ"', '"ANIMAL REP"', '"ANIMAL TISSUE"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (18, '"BP"', '"PLANT"', '"PLANT TISSUE"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (19, '"BPQ"', '"PLANT REP"', '"PLANT TISSUE"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (20, '"WE"', '"EFF"', '"EFFLUENT"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (21, '"WEQ"', '"EFF REP"', '"EFFLUENT"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (22, '"WS"', '"SW"', '"SURFACE WATER"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (23, '"WSQ"', '"SW REP"', '"SURFACE WATER"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (24, '"A9"', '"EXP-SW"', '"EXPERIMENTAL SURFACE WATER"', '"DO NOT DISPLAY OR SEND"');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (25, '"AH"', '"EXP-SED"', '"EXPERIMENTAL SEDIMENTS"', '"DO NOT DISPLAY OR SEND"');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (26, '"AF"', '"EXP-PW"', '"EXPERIMENTAL PORE WATER"', '"DO NOT DISPLAY OR SEND"');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (27, '"0C"', '"FISH"', '"TEMP FISH"', '"TEMPORARY UNTIL I TALK TO JOHN"');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (28, '"WC"', '"CANOPY WATER"', '"CANOPY WATER"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (29, '"OB"', '"BULK DEPOSITION"', '"BULK DEPOSITION"', '""');
INSERT INTO "mercuryservices_mediumtype" ("id", "nwis_code", "medium", "description", "comment") VALUES (30, '"OBQ"', '"BULK DEPOSITION REP"', '"BULK DEPOSITION"', '""');
